/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as VendasRouteImport } from './routes/vendas'
import { Route as RainforestRouteImport } from './routes/rainforest'
import { Route as OrdemServicoRouteImport } from './routes/ordem-servico'
import { Route as LotesRouteImport } from './routes/lotes'
import { Route as LoginRouteImport } from './routes/login'
import { Route as FinanceiroRouteImport } from './routes/financeiro'
import { Route as FazendasRouteImport } from './routes/fazendas'
import { Route as IndexRouteImport } from './routes/index'

const VendasRoute = VendasRouteImport.update({
  id: '/vendas',
  path: '/vendas',
  getParentRoute: () => rootRouteImport,
} as any)
const RainforestRoute = RainforestRouteImport.update({
  id: '/rainforest',
  path: '/rainforest',
  getParentRoute: () => rootRouteImport,
} as any)
const OrdemServicoRoute = OrdemServicoRouteImport.update({
  id: '/ordem-servico',
  path: '/ordem-servico',
  getParentRoute: () => rootRouteImport,
} as any)
const LotesRoute = LotesRouteImport.update({
  id: '/lotes',
  path: '/lotes',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const FinanceiroRoute = FinanceiroRouteImport.update({
  id: '/financeiro',
  path: '/financeiro',
  getParentRoute: () => rootRouteImport,
} as any)
const FazendasRoute = FazendasRouteImport.update({
  id: '/fazendas',
  path: '/fazendas',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/fazendas': typeof FazendasRoute
  '/financeiro': typeof FinanceiroRoute
  '/login': typeof LoginRoute
  '/lotes': typeof LotesRoute
  '/ordem-servico': typeof OrdemServicoRoute
  '/rainforest': typeof RainforestRoute
  '/vendas': typeof VendasRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/fazendas': typeof FazendasRoute
  '/financeiro': typeof FinanceiroRoute
  '/login': typeof LoginRoute
  '/lotes': typeof LotesRoute
  '/ordem-servico': typeof OrdemServicoRoute
  '/rainforest': typeof RainforestRoute
  '/vendas': typeof VendasRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/fazendas': typeof FazendasRoute
  '/financeiro': typeof FinanceiroRoute
  '/login': typeof LoginRoute
  '/lotes': typeof LotesRoute
  '/ordem-servico': typeof OrdemServicoRoute
  '/rainforest': typeof RainforestRoute
  '/vendas': typeof VendasRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/fazendas'
    | '/financeiro'
    | '/login'
    | '/lotes'
    | '/ordem-servico'
    | '/rainforest'
    | '/vendas'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/fazendas'
    | '/financeiro'
    | '/login'
    | '/lotes'
    | '/ordem-servico'
    | '/rainforest'
    | '/vendas'
  id:
    | '__root__'
    | '/'
    | '/fazendas'
    | '/financeiro'
    | '/login'
    | '/lotes'
    | '/ordem-servico'
    | '/rainforest'
    | '/vendas'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  FazendasRoute: typeof FazendasRoute
  FinanceiroRoute: typeof FinanceiroRoute
  LoginRoute: typeof LoginRoute
  LotesRoute: typeof LotesRoute
  OrdemServicoRoute: typeof OrdemServicoRoute
  RainforestRoute: typeof RainforestRoute
  VendasRoute: typeof VendasRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/vendas': {
      id: '/vendas'
      path: '/vendas'
      fullPath: '/vendas'
      preLoaderRoute: typeof VendasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/rainforest': {
      id: '/rainforest'
      path: '/rainforest'
      fullPath: '/rainforest'
      preLoaderRoute: typeof RainforestRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ordem-servico': {
      id: '/ordem-servico'
      path: '/ordem-servico'
      fullPath: '/ordem-servico'
      preLoaderRoute: typeof OrdemServicoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lotes': {
      id: '/lotes'
      path: '/lotes'
      fullPath: '/lotes'
      preLoaderRoute: typeof LotesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/financeiro': {
      id: '/financeiro'
      path: '/financeiro'
      fullPath: '/financeiro'
      preLoaderRoute: typeof FinanceiroRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/fazendas': {
      id: '/fazendas'
      path: '/fazendas'
      fullPath: '/fazendas'
      preLoaderRoute: typeof FazendasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  FazendasRoute: FazendasRoute,
  FinanceiroRoute: FinanceiroRoute,
  LoginRoute: LoginRoute,
  LotesRoute: LotesRoute,
  OrdemServicoRoute: OrdemServicoRoute,
  RainforestRoute: RainforestRoute,
  VendasRoute: VendasRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
